import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Banner from '../components/Banner'
import Card from '../components/Card'
import coffeeStores from '../data/coffee-stores.json'

export async function getStaticProps(context) {
  return {
    props: { coffeeStores }, // will be passed to the page component as props
  }
}

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {
  // console.log(styles);
  console.log(props);
  const bannerBtn = () => {
    console.log('Hello Banner');
  }
  return (
    <>
      <Head>
        <title>Coffee Connoisseur App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <Banner bannerBtn={bannerBtn} btnText='View store' />
        <div className={styles.heroImage}>
          <Image src='/static/hero-image.png' width={700} height={400} alt=""></Image>
        </div>

        {coffeeStores.length > 0 && <>
          <h2 className={styles.heading2}>
            Toronto Stores
          </h2>
          <div className={styles.cardLayout}>
            {props.coffeeStores.map(store => {
              return <Card
                className={styles.card}
                key={store.id}exit
                name={store.name}
                imgUrl={store.imgUrl}
                href={`/coffee_store/${store.id}`}
              />
            })}
          </div>
        </>}
      </main>
    </>
  )
}
